---
title: "NosAnalizamos"
author: "Aleix Cebrián Valero"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Carga de librerías

```{r}
library(pacman)
p_load(tidyverse, mice, knitr, validate, deducorrect, VIM, GGally)
```

# Borrar variables

```{r}
# HACER SIEMPRE
rm(list = ls())
```

# Cargar datos

```{r}
# # Averiguar la codificación
# 
# #readLines()
# 
# guess_encoding("data/NosAutoAnalizamos2022 - Hoja1.tsv")
# datos <- read_delim("data/NosAutoAnalizamos2022 - Hoja1.tsv",
#                  delim = "\t", escape_double = FALSE,
#                  trim_ws = TRUE, skip = 25)
# 
# head(datos)

library(readr)
datos <- read_delim("data/NosAutoanalizamos2026 - NosAutoanalizamos (1).tsv", 
    delim = "\t", escape_double = FALSE, 
    col_types = cols(...1 = col_skip(), ...2 = col_skip(), 
        ...3 = col_skip(), ...22 = col_skip(), 
        ...23 = col_skip()), trim_ws = TRUE, 
    skip = 27)
View(datos)

datos <- datos[1:nrow(datos)-1,] # Eliminamos la última fila que es defectuosa.

datos <- datos %>% filter(Id != "martsobm")

```

# Adecuar los datos

```{r}
datos$ALG <- str_replace_all(datos$ALG, ",", ".")
datos$ANM <- str_replace_all(datos$ANM, ",", ".")
datos$FP <- str_replace_all(datos$FP, ",", ".")
datos$DCS <- str_replace_all(datos$DCS, ",", ".")
datos$MD <- str_replace_all(datos$MD, ",", ".")

datos$ALG <- str_replace_all(datos$ALG, "NC", "3")
datos$ANM <- str_replace_all(datos$ANM, "NC", "3")
datos$FP <- str_replace_all(datos$FP, "NC", "3")
datos$DCS <- str_replace_all(datos$DCS, "NC", "3")
datos$MD <- str_replace_all(datos$MD, "NC", "3")

datos$ALG <- as.numeric(datos$ALG)
datos$ANM <- as.numeric(datos$ANM)
datos$FP <- as.numeric(datos$FP)
datos$DCS <- as.numeric(datos$DCS)
datos$MD <- as.numeric(datos$MD)
```


# Obtención de estadísticos.

```{r}
df_notas <- datos %>% select(ALG, ANM, FP, DCS, MD)

tabla_estadisticos <- bind_rows(
  # Calcular el mínimo y el máximo
df_notas %>% summarize(across(everything(), min, na.rm = T)),
df_notas %>% summarize(across(everything(), max, na.rm = T)),

# Calcular los percentiles de x
df_notas %>% 
  summarize(across(everything(), \(x) quantile(x, probs = 0.25, na.rm = TRUE))),
df_notas %>% 
  summarize(across(everything(), \(x) quantile(x, probs = 0.75, na.rm = TRUE))),

# Calcular la mediana
df_notas %>% summarize(across(everything(), median, na.rm = T)),

# Calcular la media
df_notas %>% summarize(across(everything(), mean, na.rm = T)),

# Calcular la desviación típica
df_notas %>% summarize(across(everything(), sd, na.rm = T)),
)
row.names(tabla_estadisticos) = c("Min", "Max", "P25", "P75", "Median", "Mean", 
                                  "sd")
```

# Relación entre las variables

```{r}
library(GGally)
ggpairs(df_notas, na.rm = T)

# Matrices con las correlaciones
matriz_spearman <- as.data.frame(cor(df_notas, use = "complete.obs", 
                                     method = "spearman"))
matriz_pearson <- as.data.frame(cor(df_notas, use = "complete.obs", 
                                    method = "pearson"))

# Sustituimos 1 por 0 para que no salga como máximo
matriz_spearman <- matriz_spearman %>% 
  reframe(across(everything(), \(x) replace_values(x, 1 ~ 0)))
matriz_pearson <- matriz_pearson %>% 
  reframe(across(everything(), \(x) replace_values(x, 1 ~ 0)))

row.names(matriz_spearman) <- colnames(matriz_spearman)
row.names(matriz_pearson) <- colnames(matriz_pearson)

# Hallamos el máximo y cogemos el primer valor
(matriz_spearman %>% 
    arrange(desc(across(everything()))) %>% slice_head(n = 1))[1]
(matriz_pearson %>% 
    arrange(desc(across(everything()))) %>% slice_head(n = 1))[1]

# Boxplots
ggplot(data = datos, aes(x = ALG, color = Sex)) + geom_boxplot()
ggplot(data = datos, aes(x = ANM, color = Sex)) + geom_boxplot()
ggplot(data = datos, aes(x = FP, color = Sex)) + geom_boxplot()
ggplot(data = datos, aes(x = DCS, color = Sex)) + geom_boxplot()
ggplot(data = datos, aes(x = MD, color = Sex)) + geom_boxplot()
```

# Representación alumnos con calificaciones en todas las asignaturas

```{r}
notas_full <- datos %>% select(Id, ALG, ANM, FP, DCS, MD) %>% drop_na() %>%
  pivot_longer(cols = -Id, names_to = "Asignatura", values_to = "Nota")
notas_full$Asignatura <- as.factor(notas_full$Asignatura)
notas_full$Id <- as.factor(notas_full$Id)

ggplot(notas_full, aes(x = Id, y = Nota, color = Asignatura)) +
  geom_line(aes(group = Asignatura), lwd = 0.5) + geom_point() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

